Repository ViniciusDeep/Answers-URI-Online-Judge, pull requests merged in 2018-10, with the labels that each got.

#2 Create 1071.c
  Answers/1071.c
Labels: Hacktoberfest, enhancement, good first issue

#9 SOLVED 1118.c
  Answers/1118.c
Labels: Hacktoberfest

#10 SOLVED 1930
  Answers/1930
  Answers/2059
Labels: Hacktoberfest

#11 SOLVED 1037
  Answers/1037
Labels: Hacktoberfest

#13 SOLVED 1943
  Answers/1943
Labels: Hacktoberfest, enhancement

#19 adding more python solves
  Answers/Python/1028.py
  Answers/Python/1039.py
  Answers/Python/1169.py
  Answers/Python/1294.py
  Answers/Python/1538.py
Labels: Hacktoberfest

#20 Up
  Answers/C++/1087.cpp
Labels: Hacktoberfest
